# Generated by Django 6.1.1 on 2026-10-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service_DB',
            fields=[
                ('Vehicle_No', models.CharField(primary_key=True, serialize=False)),
                ('Customer_Name', models.CharField(max_length=20)),
                ('Mobile_No', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('Date', models.DateField()),
                ('Service_Name', models.CharField()),
                ('Attender_Name', models.CharField()),
            ],
        ),
    ]
